version: '3'
services:
  zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - "2185:2181"
  kafka:
   build: .
   ports:
     - "9095:9092"
   environment:
     HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
     #KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
     KAFKA_CREATE_TOPICS: "rightdatabenchmark:1:1"
     KAFKA_ZOOKEEPER_CONNECT: zookeeper
     KAFKA_PORT: 9092
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: "mongo:latest"
  elasticsearch:
    image: "elasticsearch:alpine"
